### ISSUE TITLE
Question: alignment with the back

### ISSUE THREAD

**Issue by louis-ev** [louis-ev/Cargo-Bikes-Size-Comparator#11]
Not sure what to do here: http://localhost:5173/?bikes=[%22nakamura%22]

The Nakamura Crossover has its monkey bars welded to the frame it seems, and the length accounts for the back of the monkey bar. Which is also the case for the Decathlon R500E, but not for most other longtails (such as the multitinker 

<img width="550" alt="image" src="https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1948417/331277b8-23a7-4799-a1c2-4ca1bd049eda">

<img width="1354" alt="image" src="https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1948417/9a6d3efb-56c9-4126-b571-8ab79dabdb40">

Which makes the result deceptive in favour of the multitinker.

Any ideas on handling this situation?

**Comment by theodorefaure** [comment]
Could allowing the user to control the alignment of the bikes be a solution? Like on carsized.com.
![CleanShot 2024-05-14 at 10 30 49@2x](https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1141684/46896ad7-dc4a-4e58-b619-224ac2c186cf)

Otherwise I can't think of another solution without specifying the length measure: full bike / wheel to wheel.

**Comment by louis-ev** [comment]
The only alignment we can propose with the data we have is back, center or front. On reddit multiple people asked for a way to aligne the saddles, for example, but this means adding that information for each bike. If someone wants to contribute this, we can add it sure :)

What we could do for now is show a small range slider in the sidebar to change the horizontal alignment, per bike, when a bike is selected. So someone could change the alignements of bikes to match the saddles, for example.
We could store that information in the localstorage, so that it persists if reloading the page (by mistake). And if we display this data, someone could more easily contribute saddle position so we could add it via github?

**Comment by louis-ev** [comment]
I just asked ChatGPT 4o and got mixed results (but it understood the query easily, which is pretty good): 

<img width="1047" alt="image" src="https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1948417/91e67ee6-9ebc-43d0-b703-ec1bd045777e">

<img width="891" alt="image" src="https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1948417/2d5e0082-ca4a-45d9-a866-18dcceefc5eb">

<img width="914" alt="image" src="https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1948417/b312307b-69aa-4f12-8af2-152422da0f3c">

Overall a few are spot on, the rest are close but not quite.

**Comment by theodorefaure** [comment]
Not bad! However, saddle position is variable; in some bike photos, it might be higher than in others. Hence, it's not a reliable reference. 

The only precise reference we could get for each bike would be the frame size (all bike manufacturers provide it).

We could add those values (like on [bikeinsight](https://bikeinsights.com/)) and create a way to manually place the High-Resolution Photo on top of the generated frame drawing.

But this starts to feel really complex to just be able to compare cargo bike sizes 😄

**Comment by louis-ev** [comment]
Yes, not ideal since the saddle can move.
There was a suggestion on reddit to add individual sliders for enabled bikes, to move left/right the bike silhouette and manually adjust the position to compare. What do you think? Much less complicated and more adaptable.
Ideally this should be stored in the URL when sharing, but this is a bit of work (and would need a fix to make past URL work with the new logic, an array of objects I guess).

I see your point about the frames but I'm not sure this is useful. Or we would need much more precise measures/cropping, it is a bit sloppy right now!

**Comment by louis-ev** [comment]
Alright, added this setting to adjust the bike position individually:

![image](https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1948417/1dcdec5a-7806-422e-8c2e-5d634a21eda5)

![image](https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1948417/b448c4ba-4407-448a-bee6-d05e27cf9303)

Available online: https://bikes.louiseveillard.com/
