### ISSUE TITLE
Douze Cycles

### ISSUE THREAD

**Issue by louis-ev** [louis-ev/Cargo-Bikes-Size-Comparator#13]
@theodorefaure I have a question about the frames of the Douze Cycles LT: are they really made in France? 
According to this site they come from Portugal: https://lestransitionneurs.fr/2021/12/12/douze-cycles-devoile-ses-cargo-model-h-et-longtail-lt/
This seems more in line with their price tag as well. I can't find any info about this on their website though, do you have any that I don't?

I added the frame_made_in property because I believe the making of the frame is a clearer sign than an "assembled in" tag (most bikes are assembled in the country they are sold in, from what I gathered). So this frame_made_in seemed more informative.

What do you think?

**Comment by theodorefaure** [comment]
@louis-ev I agree; I based my pull request on the Douze bike that was already in the file but I didn't double-check the info.

**Comment by louis-ev** [comment]
Oh ok, makes sense :)
