### ISSUE TITLE
Bug de détourage sur le pédalier du petit porteur

### ISSUE THREAD

**Issue by n-b** [louis-ev/Cargo-Bikes-Size-Comparator#19]
L’intérieur du pédalier est bizarrement transparent, le cadre lui-même est effacé:

<img width="395" alt="image" src="https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/139391/536b709a-b2ae-4956-9caf-08dbf4192e3f">

Visible en ligne ici: https://bikes.louiseveillard.com/?bikes=[%22lepetitporteur%22]

Et dans le fichier source là: https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/blob/main/src/assets/bikes/lepetitporteur.png

--

(Merci mille fois pour ce projet 😻 )

**Comment by louis-ev** [comment]
Pas faux ! 
C'est le soft de détourage qui est un peu agressif… 
Je l'ai pris de là : https://www.facebook.com/photo/?fbid=1586400714758048&set=pcb.1586401438091309
Je peux corriger mais j'ai pas d'autre soft pour le faire, tu aurais ça ?
