### ISSUE TITLE
Every webp is imported as an individual JS module

### ISSUE THREAD

**Issue by tjhorner** [louis-ev/Cargo-Bikes-Size-Comparator#26]
When loading the page, it looks like each bike image and its thumbnail is loaded first as an individual JS module which just exports the URL to the associated `webp`:

<img width="630" alt="image" src="https://github.com/user-attachments/assets/936cfb09-876c-4c39-b076-fcaf726f9d19">

<img width="564" alt="image" src="https://github.com/user-attachments/assets/ea6fd1cf-6d89-4799-af28-78e87f129551">

_Then_ only after every module is imported are the images loaded:

<img width="641" alt="image" src="https://github.com/user-attachments/assets/9f79d954-cb33-4bdb-8430-6c47d6c54eeb">

This causes the page to take around 18 seconds to load.

You may wish to try the `eager` option to Vite's `import.meta.glob`, which seems like it will transform them into a static import rather than split each image into its own dynamic module: https://vitejs.dev/guide/features.html#glob-import

**Comment by louis-ev** [comment]
Ha, indeed! I thought the initial loading was a bit slow as well, thanks for your help in fixing that. I'll try that.

**Comment by louis-ev** [comment]
I'm actually not sure if I can do that… I am using [vite-imagetools](https://github.com/JonasKruckenberg/imagetools/tree/main/packages/vite) to resize images at compile time, I don't see a reason for a script to be loaded before displaying the image but I'm not seeing another way to do it in the docs above.

**Comment by tjhorner** [comment]
Why can't you use the `eager` option for `glob`? I don't see any reason it wouldn't work with that plugin, since it just turns the dynamic import static 🤔

**Comment by louis-ev** [comment]
It seems I needed `import: 'default'` as well:

```
  eager: true,
  import: 'default'
```

It's online, can you double-check?
Thanks for your help.
