### ISSUE TITLE
Feature: add sizes of the silhouette of the people

### ISSUE THREAD

**Issue by genevievecory** [louis-ev/Cargo-Bikes-Size-Comparator#28]
The rider's height is relevant for any bike. I'm only 163 cm and many bikes are really intimidating for me. The height of the silhouetted person would be great. Fantastic tool! Will publicize to the Verband Freie Lastenräder.

**Comment by louis-ev** [comment]
Hello Genevieve and thanks for your suggestion,
indeed, this would be very convenient! 
Do you think scaling proportionally the image would work? It wouldn't be perfect (for example head size is not exactly proportional to the body) but it would be much less work than drawing/loading multiple images depending on the size picked.

**Comment by genevievecory** [comment]
Yes, scaling would be fantastic! <3

**Comment by louis-ev** [comment]
Hello!
this is working, you can try it now: https://bikes.louiseveillard.com/
Let me know if this works well for you!

![image](https://github.com/user-attachments/assets/6e9b6c7a-988c-47e0-8fae-cc975ab8b0af)

**Comment by louis-ev** [comment]
Woups, let me add the "cm" suffix: 
![image](https://github.com/user-attachments/assets/36f19357-944d-40bb-9d7d-48a6634515e6)

**Comment by genevievecory** [comment]
Looks great, thanks!
![Screenshot_20241120-134606](https://github.com/user-attachments/assets/73302bc1-9b7f-4e4f-ab0a-c6701563558c)
![Screenshot_20241120-134548](https://github.com/user-attachments/assets/b6372118-8c59-40d8-a06e-c6265d95476e)


https://bsky.app/profile/did:plc:cswapgymarwyiaqauhmqbkeb/post/3layf7u2nvk2d
