### ISSUE TITLE
Feature: draw silhouette in color

### ISSUE THREAD

**Issue by louis-ev** [louis-ev/Cargo-Bikes-Size-Comparator#3]
A solid color to improve legibility, blend mode?

**Comment by louis-ev** [comment]
@ontl

Layer blending set to multiply seems better for outlines – I think we can set automatically when switching to multiply and back to default when disabling outlines.

Also, I'm thinking a checkbox "outlines" is clearer than a toggle:

<img width="1010" alt="image" src="https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1948417/f397b140-448a-4ce0-b960-04bceaaf3d4a">

**Comment by louis-ev** [comment]
Ok, so I tried giving each bike a color picked (picked arbitrarily from the frame or components then tweaked) but I'm not convinced about the results : 

<img width="1568" alt="image" src="https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1948417/5a63e58b-c401-4fcf-b403-2b4515d9314a">

<img width="1490" alt="image" src="https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/1948417/8588ad53-b723-4efe-82e9-99bc0526f1f5">

What do you think? I think I prefer with the contrasted color.

**Comment by nclm** [comment]
This is great! Would be useful if the UI highlight on the list of the left would match the colour of the outline? Right now it’s not always necessarily clear which bicycle is which.

**Comment by ontl** [comment]
Yeah I definitely found while playing around with it that I needed darker colours to stand out well against the BG.

I think it's nice for the bikes to have colours that match their frames.

But if that adds extra friction when adding bikes to the database, might want to have colours be automatically selected. Really comes down to how much work you want to do when adding each bike :)

And I like @nclm 's idea about indicating the outline colour somewhere in the UI. Could replace the green highlight, or could be like a coloured tab on the tip of each bar (but I think just full highlight replacement)
![Screenshot 2024-05-13 at 11 13 54 AM](https://github.com/louis-ev/Cargo-Bikes-Size-Comparator/assets/379506/1a37a58f-7b35-4951-a21f-3a2d7e4803ef)

**Comment by louis-ev** [comment]
Implemented ! Just the tip, full highlight made the text not legible.
